version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
        # The standard AMQP protocol port
        - 5672:5672
        # RabbitMQ Management GUI
        - 15672:15672
  generate-pi-data:
    build: data/
    restart: unless-stopped
    image: generate-pi-data
    container_name: generate-pi-data
    depends_on:
      - rabbitmq